import type { ScenarioConfig } from '../types/simulation';

export interface Preset {
  id: string;
  name: string;
  description: string;
  config: ScenarioConfig;
}

export const PRESETS: Preset[] = [
  {
    id: 'standard',
    name: 'Scénario Standard avec Variabilité Globale',
    description: 'Variabilité de la Frégate (±3NM), du vent (±4kt, ±15°), de la cible et de la vitesse hélico (±5kt).',
    config: {
      searchAreaWidth: 60,
      searchAreaHeight: 60,
      searchAreaCenterX: 0,
      searchAreaCenterY: 0,
      datumX: -15,
      datumY: -15,
      sigmaDatumX: 3.0,
      sigmaDatumY: 3.0,
      meanHeading: 45,
      meanSpeed: 16,
      sigmaT: 10,
      sigmaHeading: 15,
      sigmaSpeed: 4,
      sigmaRouteDrift: 3,
      sigmaSpeedDrift: 1,
      windDirection: 270,
      windSpeed: 15,
      sigmaWindSpeed: 4.0,
      sigmaWindDirection: 15.0,
      frigateX: 20,
      frigateY: -15,
      sigmaFrigatePosition: 3.0,
      helicoMaxSpeed: 130,
      sigmaHelicoSpeed: 5.0,
      helicoEndurance: 180,
      bingoFuelBuffer: 20,
      radarBaseRange: 12,
      gridCellSize: 0.5,
      dt: 1.0,
      numIterations: 250,
      strategy: 'TRIO',
    },
  },
  {
    id: 'storm',
    name: 'Tempête & Fort Clapot Stochastique',
    description: 'Vent violent moyen 35kt avec rafales (±8kt, ±25°). Position Frégate variable (±4NM) et dérive forte.',
    config: {
      searchAreaWidth: 70,
      searchAreaHeight: 70,
      searchAreaCenterX: 0,
      searchAreaCenterY: 0,
      datumX: -20,
      datumY: -20,
      sigmaDatumX: 4.0,
      sigmaDatumY: 4.0,
      meanHeading: 35,
      meanSpeed: 14,
      sigmaT: 15,
      sigmaHeading: 20,
      sigmaSpeed: 5,
      sigmaRouteDrift: 5,
      sigmaSpeedDrift: 2,
      windDirection: 315,
      windSpeed: 35,
      sigmaWindSpeed: 8.0,
      sigmaWindDirection: 25.0,
      frigateX: 22,
      frigateY: -20,
      sigmaFrigatePosition: 4.0,
      helicoMaxSpeed: 125,
      sigmaHelicoSpeed: 6.0,
      helicoEndurance: 180,
      bingoFuelBuffer: 25,
      radarBaseRange: 11,
      gridCellSize: 0.5,
      dt: 1.0,
      numIterations: 300,
      strategy: 'TRIO',
    },
  },
  {
    id: 'high-uncertainty',
    name: 'Forte Incertitude Datum & Frégate Stochastique',
    description: 'Forte variabilité du point de départ (±8 NM), de la Frégate (±5 NM) et de la météo.',
    config: {
      searchAreaWidth: 80,
      searchAreaHeight: 80,
      searchAreaCenterX: 0,
      searchAreaCenterY: 0,
      datumX: -20,
      datumY: -20,
      sigmaDatumX: 8.0,
      sigmaDatumY: 8.0,
      meanHeading: 45,
      meanSpeed: 16,
      sigmaT: 20,
      sigmaHeading: 25,
      sigmaSpeed: 6,
      sigmaRouteDrift: 4,
      sigmaSpeedDrift: 1.5,
      windDirection: 225,
      windSpeed: 18,
      sigmaWindSpeed: 5.0,
      sigmaWindDirection: 20.0,
      frigateX: 25,
      frigateY: -15,
      sigmaFrigatePosition: 5.0,
      helicoMaxSpeed: 135,
      sigmaHelicoSpeed: 5.0,
      helicoEndurance: 180,
      bingoFuelBuffer: 20,
      radarBaseRange: 12,
      gridCellSize: 0.5,
      dt: 1.0,
      numIterations: 350,
      strategy: 'TRIO',
    },
  },
  {
    id: 'fast-target',
    name: 'Cible Rapide & Fuyante avec Départ Aléatoire',
    description: 'Cible rapide (26 kts) et départ Frégate/Hélico aléatoire (±4 NM). Test de robustesse extrême.',
    config: {
      searchAreaWidth: 80,
      searchAreaHeight: 80,
      searchAreaCenterX: 5,
      searchAreaCenterY: 5,
      datumX: -25,
      datumY: -10,
      sigmaDatumX: 4.0,
      sigmaDatumY: 4.0,
      meanHeading: 75,
      meanSpeed: 26,
      sigmaT: 8,
      sigmaHeading: 12,
      sigmaSpeed: 4,
      sigmaRouteDrift: 2,
      sigmaSpeedDrift: 1,
      windDirection: 180,
      windSpeed: 12,
      sigmaWindSpeed: 3.0,
      sigmaWindDirection: 10.0,
      frigateX: 20,
      frigateY: -18,
      sigmaFrigatePosition: 4.0,
      helicoMaxSpeed: 140,
      sigmaHelicoSpeed: 5.0,
      helicoEndurance: 180,
      bingoFuelBuffer: 20,
      radarBaseRange: 13,
      gridCellSize: 0.5,
      dt: 1.0,
      numIterations: 250,
      strategy: 'TRIO',
    },
  },
];
